import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, Check, Fingerprint, LockKeyhole, Play, Plus } from 'lucide-react';
import { Avatar, BrandMark, CategoryIcon } from '../components/Brand';
import { Reveal } from '../components/Reveal';
import { ScenarioCard } from '../components/ScenarioCard';
import { categories, scenarios } from '../data/scenarios';
import { faqs, howSteps, reflections } from '../data/content';
import type { Category } from '../types/social';

interface LandingProps {
  onStart: (scenarioId?: string) => void;
  onExplore: (category?: Category) => void;
  onHow: () => void;
  onNote: (index: number) => void;
}

const stepImages = [
  '/images/sonix-choose.webp',
  '/images/sonix-reveal.webp',
  '/images/sonix-understand.webp',
  '/images/sonix-reconsider.webp',
];

function HowItWorks({ onStart }: { onStart: () => void }) {
  const [activeStep, setActiveStep] = useState(0);
  return <section className="how-section section-space" id="how-it-works" tabIndex={-1}><div className="container"><Reveal className="section-heading centered"><p className="eyebrow">A new kind of social.</p><h2>Less scrolling. More understanding.</h2><p>A small moment of choice. A whole new way to connect.</p></Reveal><Reveal className="how-steps"><div className="steps-connector" aria-hidden="true" />{howSteps.map((step, index) => <button className={`how-step ${activeStep === index ? 'is-active' : ''}`} key={step.title} onClick={() => setActiveStep(index)} aria-pressed={activeStep === index} aria-controls="step-explanation"><span className={`step-orb step-orb-${index}`}><img className="step-image" src={stepImages[index]} alt="" width="640" height="640" loading="lazy" decoding="async" /></span><span className="step-index">0{index + 1}</span><h3>{step.title}</h3><p>{step.subtitle}</p></button>)}</Reveal><div className="step-explanation" id="step-explanation" aria-live="polite"><AnimatePresence mode="wait" initial={false}><motion.p key={activeStep} initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}>{howSteps[activeStep].detail}</motion.p></AnimatePresence></div><button className="text-button how-try" onClick={onStart}>A new perspective, in a few minutes <ArrowUpRight size={16} /></button></div></section>;
}

function Benefits() {
  const [active, setActive] = useState(0);
  const benefits = [
    { title: 'Your voice, without the performance.', text: 'No profile to polish. No followers to impress. An anonymous space where what you think matters more than how you appear.' },
    { title: 'Context, instead of consensus.', text: 'Go beyond a percentage. See the experiences, values, and quiet reasons that can lead another person to a different choice.' },
    { title: 'A change of mind is a step forward.', text: 'Keep your answer, change it, or sit with uncertainty. Your private before-and-after journey gives every kind of reflection room to breathe.' },
  ];
  return <section className="benefits-section section-space"><div className="container benefits-layout"><Reveal className="connection-visual"><motion.div className={`connection-media connection-media-${active}`} animate={{ rotate: active === 1 ? 1.5 : active === 2 ? -1.5 : 0 }} transition={{ duration: 0.55 }}><img src="/images/sonix-connection.webp" alt="Two anonymous sculptural people in overlapping sage and lavender worlds, joined by fine orbital lines" width="1280" height="960" loading="lazy" decoding="async" /><span className="connection-media-ring ring-one" aria-hidden="true" /><span className="connection-media-ring ring-two" aria-hidden="true" /></motion.div><p>Different lives. A little common ground.</p></Reveal><Reveal className="benefits-content"><p className="eyebrow">Connection, minus the noise.</p><h2>A social space with<br />nothing to prove.</h2><p>You are more than a profile. Other people are, too.</p><div className="benefit-accordion">{benefits.map((benefit, index) => <div className={`benefit-item ${active === index ? 'is-open' : ''}`} key={benefit.title}><button onClick={() => setActive(index)} aria-expanded={active === index} aria-controls={`benefit-${index}`}><span className="benefit-number">0{index + 1}</span><span>{benefit.title}</span><Plus size={18} /></button><div id={`benefit-${index}`} hidden={active !== index}><p>{benefit.text}</p></div></div>)}</div></Reveal></div></section>;
}

export default function Landing({ onStart, onExplore, onHow, onNote }: LandingProps) {
  return <main id="main-content">
    <section className="hero" aria-labelledby="hero-title"><div className="hero-art" aria-hidden="true"><motion.img className="hero-world" src="/images/perspective-world.webp" alt="" width="1568" height="1045" fetchPriority="high" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 1.1 }} /></div><div className="container hero-container"><motion.div className="hero-copy" initial="hidden" animate="visible" variants={{ hidden: {}, visible: { transition: { staggerChildren: 0.1 } } }}><motion.p className="eyebrow hero-eyebrow" variants={{ hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0 } }}><span className="status-dot" /> Less noise. More perspective.</motion.p><motion.h1 id="hero-title" variants={{ hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7 } } }}><span className="hero-name">SoniX.</span>See the other<br /><span className="hero-accent">side of social.</span></motion.h1><motion.p className="hero-description" variants={{ hidden: { opacity: 0, y: 15 }, visible: { opacity: 1, y: 0 } }}>Real situations. Different minds. A social experience<br className="hero-copy-break" /> that starts with a choice, not a scroll.</motion.p><motion.div className="hero-cta" variants={{ hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0 } }}><button className="button button-dark" onClick={() => onStart()}>Start exploring <ArrowUpRight size={18} /></button><button className="watch-button" onClick={onHow}><span><Play size={12} fill="currentColor" /></span>How it works</button></motion.div><motion.p className="hero-reassurance" variants={{ hidden: { opacity: 0 }, visible: { opacity: 1 } }}><LockKeyhole size={12} /> No sign-up. No pressure. Just perspective.</motion.p></motion.div></div></section>
    <div className="belief-line"><div className="container"><span>A little less <span className="belief-crossed">look at me.</span></span><BrandMark /><span>A little more <strong>help me see.</strong></span></div></div>
    <HowItWorks onStart={() => onStart()} />
    <section className="featured-section section-space"><div className="container featured-layout"><Reveal className="featured-copy"><p className="eyebrow"><span className="status-dot" /> A little crossroads, for today.</p><h2>Real life.<br />Room for<br /><span className="text-sage">another view.</span></h2><p>The situations are familiar. The perspectives might surprise you. Start with a question that hits close to home.</p><button className="text-button" onClick={() => onStart(scenarios[0].id)}>Make your first choice <ArrowUpRight size={18} /></button><div className="featured-footnote"><Fingerprint size={18} strokeWidth={1.4} /><span>Anonymous by design. Human at heart.</span></div></Reveal><Reveal className="featured-orbit" delay={0.1}><ScenarioCard scenario={scenarios[0]} onOpen={() => onStart(scenarios[0].id)} /><span className="featured-orbit-dot" aria-hidden="true" /></Reveal></div></section>
    <section className="topics-section section-space"><div className="container"><Reveal className="section-heading section-heading-split"><div><p className="eyebrow">Everyday questions. Unexpected angles.</p><h2>What is on your mind?</h2></div><button className="text-button" onClick={() => onExplore()}>Explore all situations <ArrowUpRight size={17} /></button></Reveal><Reveal className="topic-orbits">{categories.map((category, index) => <button className={`topic-button topic-button-${index % 4}`} key={category} onClick={() => onExplore(category)}><span className="topic-orb"><CategoryIcon category={category} size={31} /></span><span>{category}</span><ArrowUpRight className="topic-arrow" size={13} /></button>)}</Reveal></div></section>
    <Benefits />
    <section className="voices-section section-space"><div className="container"><Reveal className="section-heading centered"><p className="eyebrow">A little shift can mean a lot.</p><h2>Different minds.<br />A more human kind of connection.</h2><p>Not here to win the conversation. Here to widen it.</p></Reveal><div className="reflection-testimonials">{reflections.map((reflection, index) => <Reveal key={reflection.label} delay={index * 0.08}><button className={`testimonial-orb testimonial-orb-${index}`} onClick={() => onNote(index)} aria-label={`Read about ${reflection.label.toLowerCase()}`}><span className="quote-mark" aria-hidden="true">&ldquo;</span><blockquote>{reflection.quote}</blockquote><Avatar index={reflection.avatar} /><span className="testimonial-label">{reflection.label}</span><ArrowUpRight className="testimonial-arrow" size={17} /></button></Reveal>)}</div><p className="voices-note">Illustrative reflections on the experience, not live user testimonials.</p></div></section>
    <section className="access-section section-space"><div className="container access-layout"><Reveal className="access-copy"><p className="eyebrow">Open to every curious mind.</p><h2>A wider perspective.<br />Not another subscription.</h2><p>The entire SoniX prototype is yours to explore. Because a new way of seeing should not come with a barrier.</p><ul className="access-inclusions"><li><Check size={16} /> Every situation. Every perspective.</li><li><Check size={16} /> A private, personal reflection journey.</li><li><Check size={16} /> No account or payment details.</li></ul></Reveal><Reveal className="access-price-wrap"><button className="access-price-orb" onClick={() => onStart()} aria-label="Start exploring the free SoniX prototype"><span className="eyebrow">A little more open.</span><strong><sup>$</sup>0<span>.</span></strong><span className="price-caption">All of the experience.<br />None of the noise.</span><span className="price-cta">Start exploring <ArrowUpRight size={17} /></span></button><span className="price-orbit" aria-hidden="true" /></Reveal></div></section>
    <section className="faq-section section-space"><div className="container faq-layout"><Reveal className="faq-heading"><p className="eyebrow">Curiosity is welcome here.</p><h2>A few things<br />you might<br />be wondering.</h2><p>Good questions deserve clear answers.</p></Reveal><Reveal className="faq-list">{faqs.map((faq, index) => <details key={faq.question} className="faq-item" open={index === 0 ? true : undefined}><summary>{faq.question}<Plus size={19} /></summary><p>{faq.answer}</p></details>)}</Reveal></div></section>
    <section className="closing-cta"><div className="cta-orbit cta-orbit-one" aria-hidden="true" /><div className="cta-orbit cta-orbit-two" aria-hidden="true" /><Reveal className="container centered"><BrandMark className="cta-mark" /><p className="eyebrow">Stay curious. Stay human.</p><h2>Your next perspective<br />is one choice away.</h2><p>See how others would choose. See what changes for you.</p><button className="button button-mint" onClick={() => onStart()}>Let's explore <ArrowUpRight size={18} /></button></Reveal></section>
  </main>;
}